export const countries = [
  {key: 'ar', value: 'Argentina'},
  {key: 'at', value: ' Austria'},
  {key: 'au', value: ' Austrlia'},
  {key: 'be', value: 'Belgium'},
  {key: 'bg', value: 'Bulgaria'},
  {key: 'br', value: 'Brazil'},
  {key: 'gb', value: 'Britain'},
  {key: 'ca', value: 'Canada'},
  {key: 'cn', value: 'China'},
  {key: 'co', value: 'Colombia'},
  {key: 'cu', value: 'Cuba'},
  {key: 'cz', value: 'Czechia'},
  {key: 'eg', value: 'Egypt'},
  {key: 'fr', value: 'France'},
  {key: 'de', value: 'Germany'},
  {key: 'gr', value: 'Greece'},
  {key: 'hk', value: 'Hong Kong'},
  {key: 'hu', value: 'Hungary'},
  {key: 'in', value: 'India'},
  {key: 'id', value: 'Indonesia'},
  {key: 'ie', value: 'Ireland'},
  {key: 'il', value: 'Israel'},
  {key: 'it', value: 'Italy'},
  {key: 'jp', value: 'Japan'},
  {key: 'kr', value: 'Korea'},
  {key: 'lv', value: 'Latvia'},
  {key: 'lt', value: 'Lithuania'},
  {key: 'my', value: 'Malasia'},
  {key: 'mx', value: 'Mexico'},
  {key: 'ma', value: 'Morocco'},
  {key: 'nl', value: 'Netherlands'},
  {key: 'nz', value: 'New Zealand'},
  {key: 'ng', value: 'Nigeria'},
  {key: 'no', value: 'Norway'},
  {key: 'ph', value: 'Philippines'},
  {key: 'pl', value: 'Poland'},
  {key: 'pt', value: 'Portugal'},
  {key: 'ro', value: 'Romania'},
  {key: 'ru', value: 'Russia'},
  {key: 'sa', value: 'Saudi Arabia'},
  {key: 'rs', value: 'Serbia'},
  {key: 'sg', value: 'Singapore'},
  {key: 'sk', value: 'Slovakia'},
  {key: 'si', value: 'Slovenia'},
  {key: 'za', value: 'South Africa'},
  {key: 'se', value: 'Sweden'},
  {key: 'ch', value: 'Switzerland'},
  {key: 'tw', value: 'Taiwan'},
  {key: 'th', value: 'Thailand'},
  {key: 'tr', value: 'Turkiye'},
  {key: 'ae', value: 'UAE'},
  {key: 'ua', value: 'Ukraine'},
  {key: 'us', value: 'USA'},
  {key: 've', value: 'Venezuela'},
];


export const category = [
  {key: 'business', value: 'Business'},
  {key: 'entertainment', value: 'Entertainment'},
  {key: 'general', value: 'General'},
  {key: 'health', value: 'Health'},
  {key: 'science', value: 'Science'},
  {key: 'sports', value: 'Sports'},
  {key: 'technology', value: 'Technology'},
];
